//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.0
//     from Assets/_Project/Settings/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Arcade
{
    public partial class @InputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Global"",
            ""id"": ""dcef0966-dff4-49e7-a970-23d5259d1a82"",
            ""actions"": [
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""d8177f08-24f3-4440-af5b-6cbb708553c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Toggle Cursor"",
                    ""type"": ""Button"",
                    ""id"": ""111e58fd-0332-48ec-a8c5-6a8f4028d3af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""cb2d9f19-398a-4951-b9c3-c9c7f5070a30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Restart"",
                    ""type"": ""Button"",
                    ""id"": ""ca909354-b0f0-41f4-b5a6-835ff5586264"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""71a3424e-444f-46f7-a84f-dff06c7d8d0c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92403178-6904-4c3e-bd0a-553260b9b699"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18a59c22-2410-49a6-b201-848edb236c4e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Toggle Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82d02491-296f-44c7-b295-9203ba7e8bb3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Toggle Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e276d68-d6d5-4ed8-8e8f-9b790f8fbbbc"",
                    ""path"": ""<Keyboard>/insert"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64626142-595b-4b40-8c62-4f62a2e73f05"",
                    ""path"": ""<Keyboard>/home"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Restart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FpsNormal"",
            ""id"": ""22122fb4-ab81-4a29-9a20-1efdb89252ad"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""9e3d2a7f-4e36-413f-a0db-967f82c11f2f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""c4a091c0-183c-4683-bd92-688cb76a48d0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Camera Height"",
                    ""type"": ""Value"",
                    ""id"": ""a90ee00d-75ff-4601-85ad-c4ce6914610c"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""8de635a7-b295-43d9-b05f-89daa55015c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Value"",
                    ""id"": ""5786bc8b-1bdb-410d-8fce-1efa022cc1d5"",
                    ""expectedControlType"": ""Digital"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f8f41772-c9a4-4700-9873-67ca7da3cdf0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Edit Positions"",
                    ""type"": ""Button"",
                    ""id"": ""c3ac06ce-bcb9-4007-b358-0e03157f5c46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Edit Content"",
                    ""type"": ""Button"",
                    ""id"": ""5eb19e11-f343-42e6-83b4-d4d04d9ceb82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""acf59875-e049-48c7-a28a-744b5b337ca9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""65f115c7-f132-43a4-88df-b6d93bc2789f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""18c43523-0b1c-4653-b74f-319a6d4f87db"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""22e04564-028a-42c3-9c72-9ea9ca8195d5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3ea590fd-28cd-40a2-ade7-a4d716c8e467"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""b1bedf90-557c-42a3-815a-b4f2deaab53f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b817b16a-6c66-4ba9-af1b-6951709c5ab6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""77e8eee0-b398-4c10-a586-737f27d84f6e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""51ea1253-0afa-4851-af30-fea86a493324"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""76ad32ba-a9c5-4991-be62-43a851579e78"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""eca59f9b-0916-4aae-ba8b-e1728489a66a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""979699a5-0170-472e-b44c-55f7930528bd"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""RFAE"",
                    ""id"": ""5bc352fa-37c6-428f-b639-dce6f5a7151f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0ed4de18-42e8-4f43-a942-a5347f5bcca5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9f363d4e-ac8b-4e7d-8ca8-1dc4f28f39c0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7d12984a-74ab-4dc8-b361-a1636b370eca"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fb2726d9-80d1-4706-b072-d261c0d8b76a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""167049f4-9b46-4dba-9f98-621ae2c93be9"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8be74ff5-e143-46a3-8557-c470a5dbc5f2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6075b4c4-c227-4352-817a-fb79a1d2fd17"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b8f287e-136d-4a76-a1bd-b1d930366911"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d6d2fec-43dd-4b65-ad81-5e0d762f8932"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23902d4e-e621-4abd-a958-022bff195241"",
                    ""path"": ""<Keyboard>/pageUp"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Edit Positions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f4b2eef-afa1-4f3b-8ec5-37441b148ee2"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Edit Positions"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""TG"",
                    ""id"": ""79870c4d-fadb-4cdb-a403-73c0ac0769c9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Height"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f307a84c-c441-4477-9b8b-b899be2ad6b2"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""dd3eb91e-9fbc-4c81-ac07-0e1bbfd9e71e"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Triggers"",
                    ""id"": ""f3b06e97-b2db-43a2-96ef-5a12f1382aa7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Height"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""a15d2d42-7acb-4f96-9a64-f0fdcdcfcf5c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""4592d88f-b596-43a1-9b33-0bad3cd34d04"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a992bda7-e0a9-4b5f-9258-4f48b27434e3"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20db50ba-9db8-4968-b4fd-b8259ce69367"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bccf0dca-76f0-4960-9e54-0dbf8103b620"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f85976a9-b3d0-4e6d-aca9-71fdc9393424"",
                    ""path"": ""<Keyboard>/pageDown"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Edit Content"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FpsEditPositions"",
            ""id"": ""826403ab-f082-4a58-8a51-3a726b972945"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3c404557-4b9e-4d5c-b5ef-b2e19649b1d5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""5bd2bcf2-81e7-487d-a7bb-9efd6a463306"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Grab"",
                    ""type"": ""Button"",
                    ""id"": ""da98b889-a257-4260-bdb7-c2d25d037c14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""IKJL"",
                    ""id"": ""e2dbf37a-fe69-4f24-907b-785db15190c5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b0ee920e-807b-4a67-a268-5ae3d1cd35cb"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6aab8201-b777-408d-a0cc-1bf61d49b99d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d22e5217-f071-4ce6-9b1c-6f543611f61e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fcc18843-1103-4a63-b59e-375348100c0b"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a32c1c88-d8b1-4753-b208-b49d17aac77b"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""UO"",
                    ""id"": ""405e8f8e-765a-4380-be52-32c34ebee78c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5b6b77dd-c8b5-4336-88aa-3e986721dfde"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""267ba5e7-001a-4917-a6c9-7ad831e33a53"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Shoulders"",
                    ""id"": ""341a6c34-3c4a-45be-a2fe-b950191f5f2b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c8fd3857-6235-4e6a-9c95-c5420b95dc87"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""645fdfac-6ae9-4d08-b2b1-2c2c6b2be365"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0990e09d-e138-4b42-8abe-72a9e4b5a367"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6741b1b1-5301-4dc5-81f1-d07abd193117"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""803e54e5-a269-486a-aa6a-8789717c70f5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Grab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FpsEditContent"",
            ""id"": ""3a8d13a1-682d-432c-8cad-da698e08c73e"",
            ""actions"": [
                {
                    ""name"": ""ApplyOrAdd"",
                    ""type"": ""Button"",
                    ""id"": ""bd1774bb-dbc8-40fc-af12-be359f289094"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Remove"",
                    ""type"": ""Button"",
                    ""id"": ""ed032eca-4259-4588-8e13-fc4c9fabaa21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9ce9edd9-67e4-47bd-9818-3870e4e57309"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""ApplyOrAdd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c345d49-424b-4ab4-b198-6c9e953dfbdc"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Remove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CylNormal"",
            ""id"": ""cee92ad0-24ac-4ae8-b5bb-9fd31a285831"",
            ""actions"": [
                {
                    ""name"": ""Navigation Vertical"",
                    ""type"": ""Value"",
                    ""id"": ""e1f0c0ad-badd-44d1-a958-cb657e58637d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Navigation Horizontal"",
                    ""type"": ""Value"",
                    ""id"": ""ab61ee91-1a7d-471b-bc23-8f1c4a0e8260"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""ec7b6c22-2306-4be1-90de-d60a48c1f2bf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Camera Height"",
                    ""type"": ""Value"",
                    ""id"": ""b794dfff-5179-436f-b532-d0afa18c37a8"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""5c66f33d-85c8-49d5-87ec-8b63f8ed1eee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WS"",
                    ""id"": ""05099181-0021-4413-8078-44e1c7ef9f1f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f3ade314-c401-40d7-9775-6eeb0cfd6c5a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8d1c0ab6-fc80-4c8a-a037-8855f834cce3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""8da28b44-fd4e-4869-9af8-293cf1218fee"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""725e64b4-65e6-4ef3-94ac-9c4d6f7582e1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4e166e49-4761-415c-a091-6581f34fced1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left Stick"",
                    ""id"": ""8f73a6aa-397c-4b77-9b67-8c08db46c72a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""089ee213-684e-4e55-9a13-2fd3a3ba25e7"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""20c36024-7d77-43dc-b64a-b6613a82f62a"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigation Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1868423f-1af1-4ae5-90e4-4c855df6bc04"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""RFAE"",
                    ""id"": ""928bd405-c860-4f27-aa41-02db7f658248"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c1a9e278-11cf-4338-9ed6-2f12f23ced36"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""65998c15-72ed-4441-879b-34098d1bc31e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ad275b4f-d8d4-42f1-b3eb-3baee334cd01"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""dd0dc889-8276-4d2e-abc5-a33121c73045"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2a412500-fde2-47b3-bf9c-73f3027249c5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""TG"",
                    ""id"": ""32782cf7-c276-4a78-90a2-f479766e39f4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Height"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0c3ced21-82b0-4fa9-8cd6-e40b12b063f0"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c6474c29-88d2-491f-b759-7a4f0b1de030"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Triggers"",
                    ""id"": ""412ac7a8-42e3-4fc9-a11b-4fa7a0d6378c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera Height"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""b9a243ce-4ec4-4c94-bec7-4d1c78fc4ad5"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""f5a9fba8-1b74-429c-bd3c-d3420808b02c"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Camera Height"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a4b979a9-91a6-4aed-bc66-9bab7490a5b5"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d8d3697-a117-4fb6-af5e-b2b848b5551b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7dc06803-7870-4a8d-bfef-33a7c084dd8f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""b76e3822-8474-4c2b-a7e0-4e0790b92080"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6a011495-7033-4d48-b7cb-48916ad4dc14"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d86cc60b-79a5-46f8-985e-2d8f3a95ed4b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""eccc8847-1486-49fb-b442-e1b0d66555b1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""053853c8-3df8-4c1c-95f3-e72ce8cc5d4a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f6a65dc4-4309-47b9-88f4-595edfbaa098"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard & Mouse"",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left Stick"",
                    ""id"": ""28430306-508e-46e6-8109-95035133f7b6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7f9762f5-77c1-4f27-93ac-2efb169650b7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f817b234-a513-4848-9537-cf005ff89bf3"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigation Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard & Mouse"",
            ""bindingGroup"": ""Keyboard & Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Continuous Move"",
            ""bindingGroup"": ""Continuous Move"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Generic XR Controller"",
            ""bindingGroup"": ""Generic XR Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<WMRHMD>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Noncontinuous Move"",
            ""bindingGroup"": ""Noncontinuous Move"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Global
            m_Global = asset.FindActionMap("Global", throwIfNotFound: true);
            m_Global_Quit = m_Global.FindAction("Quit", throwIfNotFound: true);
            m_Global_ToggleCursor = m_Global.FindAction("Toggle Cursor", throwIfNotFound: true);
            m_Global_Reload = m_Global.FindAction("Reload", throwIfNotFound: true);
            m_Global_Restart = m_Global.FindAction("Restart", throwIfNotFound: true);
            // FpsNormal
            m_FpsNormal = asset.FindActionMap("FpsNormal", throwIfNotFound: true);
            m_FpsNormal_Movement = m_FpsNormal.FindAction("Movement", throwIfNotFound: true);
            m_FpsNormal_Look = m_FpsNormal.FindAction("Look", throwIfNotFound: true);
            m_FpsNormal_CameraHeight = m_FpsNormal.FindAction("Camera Height", throwIfNotFound: true);
            m_FpsNormal_Interact = m_FpsNormal.FindAction("Interact", throwIfNotFound: true);
            m_FpsNormal_Sprint = m_FpsNormal.FindAction("Sprint", throwIfNotFound: true);
            m_FpsNormal_Jump = m_FpsNormal.FindAction("Jump", throwIfNotFound: true);
            m_FpsNormal_EditPositions = m_FpsNormal.FindAction("Edit Positions", throwIfNotFound: true);
            m_FpsNormal_EditContent = m_FpsNormal.FindAction("Edit Content", throwIfNotFound: true);
            // FpsEditPositions
            m_FpsEditPositions = asset.FindActionMap("FpsEditPositions", throwIfNotFound: true);
            m_FpsEditPositions_Move = m_FpsEditPositions.FindAction("Move", throwIfNotFound: true);
            m_FpsEditPositions_Rotate = m_FpsEditPositions.FindAction("Rotate", throwIfNotFound: true);
            m_FpsEditPositions_Grab = m_FpsEditPositions.FindAction("Grab", throwIfNotFound: true);
            // FpsEditContent
            m_FpsEditContent = asset.FindActionMap("FpsEditContent", throwIfNotFound: true);
            m_FpsEditContent_ApplyOrAdd = m_FpsEditContent.FindAction("ApplyOrAdd", throwIfNotFound: true);
            m_FpsEditContent_Remove = m_FpsEditContent.FindAction("Remove", throwIfNotFound: true);
            // CylNormal
            m_CylNormal = asset.FindActionMap("CylNormal", throwIfNotFound: true);
            m_CylNormal_NavigationVertical = m_CylNormal.FindAction("Navigation Vertical", throwIfNotFound: true);
            m_CylNormal_NavigationHorizontal = m_CylNormal.FindAction("Navigation Horizontal", throwIfNotFound: true);
            m_CylNormal_Look = m_CylNormal.FindAction("Look", throwIfNotFound: true);
            m_CylNormal_CameraHeight = m_CylNormal.FindAction("Camera Height", throwIfNotFound: true);
            m_CylNormal_Interact = m_CylNormal.FindAction("Interact", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Global
        private readonly InputActionMap m_Global;
        private IGlobalActions m_GlobalActionsCallbackInterface;
        private readonly InputAction m_Global_Quit;
        private readonly InputAction m_Global_ToggleCursor;
        private readonly InputAction m_Global_Reload;
        private readonly InputAction m_Global_Restart;
        public struct GlobalActions
        {
            private @InputActions m_Wrapper;
            public GlobalActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Quit => m_Wrapper.m_Global_Quit;
            public InputAction @ToggleCursor => m_Wrapper.m_Global_ToggleCursor;
            public InputAction @Reload => m_Wrapper.m_Global_Reload;
            public InputAction @Restart => m_Wrapper.m_Global_Restart;
            public InputActionMap Get() { return m_Wrapper.m_Global; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GlobalActions set) { return set.Get(); }
            public void SetCallbacks(IGlobalActions instance)
            {
                if (m_Wrapper.m_GlobalActionsCallbackInterface != null)
                {
                    @Quit.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnQuit;
                    @Quit.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnQuit;
                    @Quit.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnQuit;
                    @ToggleCursor.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnToggleCursor;
                    @ToggleCursor.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnToggleCursor;
                    @ToggleCursor.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnToggleCursor;
                    @Reload.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnReload;
                    @Reload.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnReload;
                    @Reload.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnReload;
                    @Restart.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnRestart;
                    @Restart.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnRestart;
                    @Restart.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnRestart;
                }
                m_Wrapper.m_GlobalActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Quit.started += instance.OnQuit;
                    @Quit.performed += instance.OnQuit;
                    @Quit.canceled += instance.OnQuit;
                    @ToggleCursor.started += instance.OnToggleCursor;
                    @ToggleCursor.performed += instance.OnToggleCursor;
                    @ToggleCursor.canceled += instance.OnToggleCursor;
                    @Reload.started += instance.OnReload;
                    @Reload.performed += instance.OnReload;
                    @Reload.canceled += instance.OnReload;
                    @Restart.started += instance.OnRestart;
                    @Restart.performed += instance.OnRestart;
                    @Restart.canceled += instance.OnRestart;
                }
            }
        }
        public GlobalActions @Global => new GlobalActions(this);

        // FpsNormal
        private readonly InputActionMap m_FpsNormal;
        private IFpsNormalActions m_FpsNormalActionsCallbackInterface;
        private readonly InputAction m_FpsNormal_Movement;
        private readonly InputAction m_FpsNormal_Look;
        private readonly InputAction m_FpsNormal_CameraHeight;
        private readonly InputAction m_FpsNormal_Interact;
        private readonly InputAction m_FpsNormal_Sprint;
        private readonly InputAction m_FpsNormal_Jump;
        private readonly InputAction m_FpsNormal_EditPositions;
        private readonly InputAction m_FpsNormal_EditContent;
        public struct FpsNormalActions
        {
            private @InputActions m_Wrapper;
            public FpsNormalActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_FpsNormal_Movement;
            public InputAction @Look => m_Wrapper.m_FpsNormal_Look;
            public InputAction @CameraHeight => m_Wrapper.m_FpsNormal_CameraHeight;
            public InputAction @Interact => m_Wrapper.m_FpsNormal_Interact;
            public InputAction @Sprint => m_Wrapper.m_FpsNormal_Sprint;
            public InputAction @Jump => m_Wrapper.m_FpsNormal_Jump;
            public InputAction @EditPositions => m_Wrapper.m_FpsNormal_EditPositions;
            public InputAction @EditContent => m_Wrapper.m_FpsNormal_EditContent;
            public InputActionMap Get() { return m_Wrapper.m_FpsNormal; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FpsNormalActions set) { return set.Get(); }
            public void SetCallbacks(IFpsNormalActions instance)
            {
                if (m_Wrapper.m_FpsNormalActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnMovement;
                    @Look.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnLook;
                    @CameraHeight.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnCameraHeight;
                    @CameraHeight.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnCameraHeight;
                    @CameraHeight.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnCameraHeight;
                    @Interact.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnInteract;
                    @Sprint.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnSprint;
                    @Sprint.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnSprint;
                    @Sprint.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnSprint;
                    @Jump.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnJump;
                    @EditPositions.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnEditPositions;
                    @EditPositions.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnEditPositions;
                    @EditPositions.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnEditPositions;
                    @EditContent.started -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnEditContent;
                    @EditContent.performed -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnEditContent;
                    @EditContent.canceled -= m_Wrapper.m_FpsNormalActionsCallbackInterface.OnEditContent;
                }
                m_Wrapper.m_FpsNormalActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @CameraHeight.started += instance.OnCameraHeight;
                    @CameraHeight.performed += instance.OnCameraHeight;
                    @CameraHeight.canceled += instance.OnCameraHeight;
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                    @Sprint.started += instance.OnSprint;
                    @Sprint.performed += instance.OnSprint;
                    @Sprint.canceled += instance.OnSprint;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @EditPositions.started += instance.OnEditPositions;
                    @EditPositions.performed += instance.OnEditPositions;
                    @EditPositions.canceled += instance.OnEditPositions;
                    @EditContent.started += instance.OnEditContent;
                    @EditContent.performed += instance.OnEditContent;
                    @EditContent.canceled += instance.OnEditContent;
                }
            }
        }
        public FpsNormalActions @FpsNormal => new FpsNormalActions(this);

        // FpsEditPositions
        private readonly InputActionMap m_FpsEditPositions;
        private IFpsEditPositionsActions m_FpsEditPositionsActionsCallbackInterface;
        private readonly InputAction m_FpsEditPositions_Move;
        private readonly InputAction m_FpsEditPositions_Rotate;
        private readonly InputAction m_FpsEditPositions_Grab;
        public struct FpsEditPositionsActions
        {
            private @InputActions m_Wrapper;
            public FpsEditPositionsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_FpsEditPositions_Move;
            public InputAction @Rotate => m_Wrapper.m_FpsEditPositions_Rotate;
            public InputAction @Grab => m_Wrapper.m_FpsEditPositions_Grab;
            public InputActionMap Get() { return m_Wrapper.m_FpsEditPositions; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FpsEditPositionsActions set) { return set.Get(); }
            public void SetCallbacks(IFpsEditPositionsActions instance)
            {
                if (m_Wrapper.m_FpsEditPositionsActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnMove;
                    @Rotate.started -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnRotate;
                    @Rotate.performed -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnRotate;
                    @Rotate.canceled -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnRotate;
                    @Grab.started -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnGrab;
                    @Grab.performed -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnGrab;
                    @Grab.canceled -= m_Wrapper.m_FpsEditPositionsActionsCallbackInterface.OnGrab;
                }
                m_Wrapper.m_FpsEditPositionsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @Rotate.started += instance.OnRotate;
                    @Rotate.performed += instance.OnRotate;
                    @Rotate.canceled += instance.OnRotate;
                    @Grab.started += instance.OnGrab;
                    @Grab.performed += instance.OnGrab;
                    @Grab.canceled += instance.OnGrab;
                }
            }
        }
        public FpsEditPositionsActions @FpsEditPositions => new FpsEditPositionsActions(this);

        // FpsEditContent
        private readonly InputActionMap m_FpsEditContent;
        private IFpsEditContentActions m_FpsEditContentActionsCallbackInterface;
        private readonly InputAction m_FpsEditContent_ApplyOrAdd;
        private readonly InputAction m_FpsEditContent_Remove;
        public struct FpsEditContentActions
        {
            private @InputActions m_Wrapper;
            public FpsEditContentActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @ApplyOrAdd => m_Wrapper.m_FpsEditContent_ApplyOrAdd;
            public InputAction @Remove => m_Wrapper.m_FpsEditContent_Remove;
            public InputActionMap Get() { return m_Wrapper.m_FpsEditContent; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(FpsEditContentActions set) { return set.Get(); }
            public void SetCallbacks(IFpsEditContentActions instance)
            {
                if (m_Wrapper.m_FpsEditContentActionsCallbackInterface != null)
                {
                    @ApplyOrAdd.started -= m_Wrapper.m_FpsEditContentActionsCallbackInterface.OnApplyOrAdd;
                    @ApplyOrAdd.performed -= m_Wrapper.m_FpsEditContentActionsCallbackInterface.OnApplyOrAdd;
                    @ApplyOrAdd.canceled -= m_Wrapper.m_FpsEditContentActionsCallbackInterface.OnApplyOrAdd;
                    @Remove.started -= m_Wrapper.m_FpsEditContentActionsCallbackInterface.OnRemove;
                    @Remove.performed -= m_Wrapper.m_FpsEditContentActionsCallbackInterface.OnRemove;
                    @Remove.canceled -= m_Wrapper.m_FpsEditContentActionsCallbackInterface.OnRemove;
                }
                m_Wrapper.m_FpsEditContentActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ApplyOrAdd.started += instance.OnApplyOrAdd;
                    @ApplyOrAdd.performed += instance.OnApplyOrAdd;
                    @ApplyOrAdd.canceled += instance.OnApplyOrAdd;
                    @Remove.started += instance.OnRemove;
                    @Remove.performed += instance.OnRemove;
                    @Remove.canceled += instance.OnRemove;
                }
            }
        }
        public FpsEditContentActions @FpsEditContent => new FpsEditContentActions(this);

        // CylNormal
        private readonly InputActionMap m_CylNormal;
        private ICylNormalActions m_CylNormalActionsCallbackInterface;
        private readonly InputAction m_CylNormal_NavigationVertical;
        private readonly InputAction m_CylNormal_NavigationHorizontal;
        private readonly InputAction m_CylNormal_Look;
        private readonly InputAction m_CylNormal_CameraHeight;
        private readonly InputAction m_CylNormal_Interact;
        public struct CylNormalActions
        {
            private @InputActions m_Wrapper;
            public CylNormalActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @NavigationVertical => m_Wrapper.m_CylNormal_NavigationVertical;
            public InputAction @NavigationHorizontal => m_Wrapper.m_CylNormal_NavigationHorizontal;
            public InputAction @Look => m_Wrapper.m_CylNormal_Look;
            public InputAction @CameraHeight => m_Wrapper.m_CylNormal_CameraHeight;
            public InputAction @Interact => m_Wrapper.m_CylNormal_Interact;
            public InputActionMap Get() { return m_Wrapper.m_CylNormal; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CylNormalActions set) { return set.Get(); }
            public void SetCallbacks(ICylNormalActions instance)
            {
                if (m_Wrapper.m_CylNormalActionsCallbackInterface != null)
                {
                    @NavigationVertical.started -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnNavigationVertical;
                    @NavigationVertical.performed -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnNavigationVertical;
                    @NavigationVertical.canceled -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnNavigationVertical;
                    @NavigationHorizontal.started -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnNavigationHorizontal;
                    @NavigationHorizontal.performed -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnNavigationHorizontal;
                    @NavigationHorizontal.canceled -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnNavigationHorizontal;
                    @Look.started -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnLook;
                    @CameraHeight.started -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnCameraHeight;
                    @CameraHeight.performed -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnCameraHeight;
                    @CameraHeight.canceled -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnCameraHeight;
                    @Interact.started -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnInteract;
                    @Interact.performed -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnInteract;
                    @Interact.canceled -= m_Wrapper.m_CylNormalActionsCallbackInterface.OnInteract;
                }
                m_Wrapper.m_CylNormalActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @NavigationVertical.started += instance.OnNavigationVertical;
                    @NavigationVertical.performed += instance.OnNavigationVertical;
                    @NavigationVertical.canceled += instance.OnNavigationVertical;
                    @NavigationHorizontal.started += instance.OnNavigationHorizontal;
                    @NavigationHorizontal.performed += instance.OnNavigationHorizontal;
                    @NavigationHorizontal.canceled += instance.OnNavigationHorizontal;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @CameraHeight.started += instance.OnCameraHeight;
                    @CameraHeight.performed += instance.OnCameraHeight;
                    @CameraHeight.canceled += instance.OnCameraHeight;
                    @Interact.started += instance.OnInteract;
                    @Interact.performed += instance.OnInteract;
                    @Interact.canceled += instance.OnInteract;
                }
            }
        }
        public CylNormalActions @CylNormal => new CylNormalActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard & Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        private int m_GamepadSchemeIndex = -1;
        public InputControlScheme GamepadScheme
        {
            get
            {
                if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
                return asset.controlSchemes[m_GamepadSchemeIndex];
            }
        }
        private int m_ContinuousMoveSchemeIndex = -1;
        public InputControlScheme ContinuousMoveScheme
        {
            get
            {
                if (m_ContinuousMoveSchemeIndex == -1) m_ContinuousMoveSchemeIndex = asset.FindControlSchemeIndex("Continuous Move");
                return asset.controlSchemes[m_ContinuousMoveSchemeIndex];
            }
        }
        private int m_GenericXRControllerSchemeIndex = -1;
        public InputControlScheme GenericXRControllerScheme
        {
            get
            {
                if (m_GenericXRControllerSchemeIndex == -1) m_GenericXRControllerSchemeIndex = asset.FindControlSchemeIndex("Generic XR Controller");
                return asset.controlSchemes[m_GenericXRControllerSchemeIndex];
            }
        }
        private int m_NoncontinuousMoveSchemeIndex = -1;
        public InputControlScheme NoncontinuousMoveScheme
        {
            get
            {
                if (m_NoncontinuousMoveSchemeIndex == -1) m_NoncontinuousMoveSchemeIndex = asset.FindControlSchemeIndex("Noncontinuous Move");
                return asset.controlSchemes[m_NoncontinuousMoveSchemeIndex];
            }
        }
        public interface IGlobalActions
        {
            void OnQuit(InputAction.CallbackContext context);
            void OnToggleCursor(InputAction.CallbackContext context);
            void OnReload(InputAction.CallbackContext context);
            void OnRestart(InputAction.CallbackContext context);
        }
        public interface IFpsNormalActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnCameraHeight(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
            void OnSprint(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnEditPositions(InputAction.CallbackContext context);
            void OnEditContent(InputAction.CallbackContext context);
        }
        public interface IFpsEditPositionsActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
            void OnGrab(InputAction.CallbackContext context);
        }
        public interface IFpsEditContentActions
        {
            void OnApplyOrAdd(InputAction.CallbackContext context);
            void OnRemove(InputAction.CallbackContext context);
        }
        public interface ICylNormalActions
        {
            void OnNavigationVertical(InputAction.CallbackContext context);
            void OnNavigationHorizontal(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnCameraHeight(InputAction.CallbackContext context);
            void OnInteract(InputAction.CallbackContext context);
        }
    }
}
